language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov pandas
# command to run tests
script: py.test --cov=spc tests
